//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilgiYarismasi.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BilgiYarismasiEntities2 : DbContext
    {
        public BilgiYarismasiEntities2()
            : base("name=BilgiYarismasiEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Cevap> Cevap { get; set; }
        public virtual DbSet<Konu> Konu { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<Soru> Soru { get; set; }
        public virtual DbSet<YarismaSoru> YarismaSoru { get; set; }
        public virtual DbSet<YarismaSoruCevap> YarismaSoruCevap { get; set; }
        public virtual DbSet<Masa> Masa { get; set; }
        public virtual DbSet<MasaKullanici> MasaKullanici { get; set; }
        public virtual DbSet<Yarisma> Yarisma { get; set; }
        public virtual DbSet<VKullaniciPuan> VKullaniciPuan { get; set; }
        public virtual DbSet<Ayarlar> Ayarlar { get; set; }
        public virtual DbSet<VKullaniciPuanTipli> VKullaniciPuanTipli { get; set; }
    }
}
