//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilgiYarismasi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasaKullanici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasaKullanici()
        {
            this.Yarisma = new HashSet<Yarisma>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid MasaId { get; set; }
        public System.Guid KullaniciId { get; set; }
        public int Tip { get; set; }
        public int SiraNo { get; set; }
        public Nullable<System.DateTime> Ping { get; set; }
        public System.DateTime KayitTarihi { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        public virtual Masa Masa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yarisma> Yarisma { get; set; }
    }
}
