//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilgiYarismasi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class YarismaSoruCevap
    {
        public System.Guid Id { get; set; }
        public System.Guid YarismaSoruId { get; set; }
        public System.Guid CevapId { get; set; }
    
        public virtual Cevap Cevap { get; set; }
        public virtual YarismaSoru YarismaSoru { get; set; }
    }
}
