//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilgiYarismasi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class YarismaSoru
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YarismaSoru()
        {
            this.YarismaSoruCevap = new HashSet<YarismaSoruCevap>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid YarismaId { get; set; }
        public System.Guid SoruId { get; set; }
        public Nullable<int> SiraNo { get; set; }
        public Nullable<System.Guid> CevapId { get; set; }
        public Nullable<int> Puan { get; set; }
        public Nullable<System.DateTime> GosterimTarihi { get; set; }
    
        public virtual Cevap Cevap { get; set; }
        public virtual Soru Soru { get; set; }
        public virtual Yarisma Yarisma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YarismaSoruCevap> YarismaSoruCevap { get; set; }
    }
}
